name: ci-cd-golang-workflow
on: 
  pull_request:
    branches:
      - develop

jobs: 
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go env -w GO111MODULE=auto
      - run: go test ./main
      - run: go run ./main/math.go