name: ci-cd-golang-workflow
on: 
  pull_request:
    branches:
      - develop
  
jobs: 
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.2
      - run: go env -w GO111MODULE=auto
      - run: go test ./main
      - run: go run ./main/math.go