name: ci-cd-golang-workflow
on: 
  pull_request:
    branches:
      - develop

jobs: 
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go env -w GO111MODULE=auto
      - run: go test ./main
      - run: go run ./main/math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: deharahawa/ci-cd-studies/app:latest